[package]
name = "octoscript_catalog"
version = "0.1.0"
edition = "2021"

[lib]
name = "octoscript_catalog"
crate-type = ["cdylib", "rlib"]

[dependencies]
octoscript-render = { path = "/Users/yuechen/home/Octoscript-Makepad/crates/octoscript-render" }
jni = "0.21"
serde_json = "1.0.151"
ureq = { version = "2", features = ["tls"] }

[profile.release]
opt-level = 2
